DATASET_PROFILES_DIR = "src\\results\\dataset_profiles"
POLICY_RESULTS_DIR = "src\\results\\policy_results"
PIPELINE_RESULT_DIR = POLICY_RESULTS_DIR + "\\self_trained"
PAPER_RESULTS_DIR = POLICY_RESULTS_DIR + "\\d3rlpy_paper"
DEFAULT_CONFIG_PATH = "src\\configs\\cql_default.yaml"
DEFAULT_FIGURE_OUTPUT_DIR = "src\\results\\figures"
